[package]
name = "pdf_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
pdf = "0.8.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.7"
chrono = "0.4"
walkdir = "2.3" 